"""create pairing_codes table

Revision ID: 0b60711c3388
Revises: 9396065b44a9
Create Date: 2025-10-03 11:53:35.563813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b60711c3388'
down_revision: Union[str, None] = '9396065b44a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairing_codes',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('duck_color', sa.String(length=7), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_pairing_expires_at', 'pairing_codes', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pairing_expires_at', table_name='pairing_codes')
    op.drop_table('pairing_codes')
    # ### end Alembic commands ###
