name: CI
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx anyio

      - name: Run tests
        working-directory: backend
        env:
          ENV: dev
          SECRET_KEY: ci-secret
          ACCESS_TOKEN_EXPIRE_MINUTES: "60"
          DATABASE_URL: "sqlite+aiosqlite:///./var/dev.db"
        run: pytest -q